# Generated by Django 5.2 on 2026-02-19 19:15

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MID", "Mid"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("file_type", models.CharField(max_length=10)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("minio_key", models.CharField(max_length=512, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("INDEXED", "Indexed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MID", "Mid"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["security_level", "status"],
                name="documents_d_securit_c722ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="documents_d_uploade_2fe388_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["security_level"], name="documents_d_securit_a5a109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="documents_d_documen_8ea6ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["security_level", "document"],
                name="documents_d_securit_22f15a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
