# Generated by Django 5.2 on 2026-02-17 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MID", "Mid"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("file_type", models.CharField(max_length=10)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("minio_key", models.CharField(max_length=512, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("INDEXED", "Indexed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["security_level", "status"],
                        name="documents_d_securit_c722ad_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "-created_at"],
                        name="documents_d_uploade_2fe388_idx",
                    ),
                ],
            },
        ),
    ]
