# Generated by Django 5.2 on 2026-02-17 18:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MID", "Mid"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["security_level"], name="documents_d_securit_a5a109_idx"
                    ),
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="documents_d_documen_8ea6ce_idx",
                    ),
                    models.Index(
                        fields=["security_level", "document"],
                        name="documents_d_securit_22f15a_idx",
                    ),
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
