# rag/models.py
from django.db import models

from documents.models import Document
from users.models import User

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rag_chats")
    title = models.CharField(max_length=255, blank=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return self.title or f"Chat {self.id}"
    
class QueryHistory(models.Model):
    """
    Audit log for every RAG query.
    Used for quality monitoring, analytics, and compliance.
    """
    user = models.ForeignKey(User,  on_delete=models.SET_NULL, null=True, related_name="rag_queries")
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name="messages", null=True)
    
    query = models.TextField()
    query_embedding = models.JSONField(
        null=True, 
        blank=True,
        help_text="384-dimensional query embedding for reproducibility"
    )
    
    # Retrieved context
    retrieved_chunk_count = models.PositiveIntegerField(default=0)
    retrieved_chunk_ids = models.JSONField(
        default=list,
        help_text="IDs of chunks used for answer generation"
    )
    
    # Response details
    response = models.TextField()
    response_source = models.CharField(
        max_length=20,
        choices=[
            ("LLM", "Generated by Local LLM"),
            ("EXTRACTIVE", "Extractive summary (fallback)"),
            ("ERROR", "Error response"),
        ],
        default="LLM"
    )
    
    # Performance metrics
    latency_ms = models.PositiveIntegerField(default=0)
    token_count = models.PositiveIntegerField(default=0)
    
    # Quality & audit
    security_level = models.CharField(
        max_length=10,
        choices=Document.SecurityLevel.choices,
        default=Document.SecurityLevel.LOW
    )
    is_flagged = models.BooleanField(
        default=False,
        help_text="Flagged for manual review (e.g., low confidence)"
    )
    flag_reason = models.TextField(blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "-created_at"]),
            models.Index(fields=["security_level", "-created_at"]),
            models.Index(fields=["is_flagged"]),
        ]
    
    def __str__(self):
        return f"Query by {self.user.username if self.user else 'Anonymous'} at {self.created_at}"