# Generated by Django 5.2 on 2026-02-20 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                (
                    "query_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="384-dimensional query embedding for reproducibility",
                        null=True,
                    ),
                ),
                ("retrieved_chunk_count", models.PositiveIntegerField(default=0)),
                (
                    "retrieved_chunk_ids",
                    models.JSONField(
                        default=list,
                        help_text="IDs of chunks used for answer generation",
                    ),
                ),
                ("response", models.TextField()),
                (
                    "response_source",
                    models.CharField(
                        choices=[
                            ("LLM", "Generated by Local LLM"),
                            ("EXTRACTIVE", "Extractive summary (fallback)"),
                            ("ERROR", "Error response"),
                        ],
                        default="LLM",
                        max_length=20,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("token_count", models.PositiveIntegerField(default=0)),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MID", "Mid"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged for manual review (e.g., low confidence)",
                    ),
                ),
                ("flag_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rag_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rag_queryhi_user_id_7cfaad_idx",
                    ),
                    models.Index(
                        fields=["security_level", "-created_at"],
                        name="rag_queryhi_securit_e301ed_idx",
                    ),
                    models.Index(
                        fields=["is_flagged"], name="rag_queryhi_is_flag_a55013_idx"
                    ),
                ],
            },
        ),
    ]
